### ISSUE TITLE
Unexpected Error: PlatformException

### ISSUE THREAD

**Issue by athosmoreno** [authpass/authpass#105]
I am using this app on Kubuntu 20.04 installed through snap with a local KeePass file.

Upon opening the application I am facing this error. Upon clicking two or three times on Ok it works.
![image](https://user-images.githubusercontent.com/6440060/87235329-6cc99780-c3b1-11ea-9fb3-4312eea85af0.png)

After opening my KDBX file, I am facing this error and any keystroke or mouse activity triggers it, but after a while it let me type the password. This error also happens sometimes when opening a password.

![image](https://user-images.githubusercontent.com/6440060/87235347-9b477280-c3b1-11ea-8f4d-6171a78336f5.png)

**Comment by hpoul** [comment]
Weird, is this a default installation? I've thought all Linux desktop would have a secret service (org.freedesktop.Secret.Service) :-/ (eg gnome-keyring, ksecretsserviced)

Looks like this is not that common in non-gnome systems :-( anyway, it's technically only needed for cloud storage (because it's used to store auth tokens) that's why for local password files it is still working after clicking away the error messages.. so it's just a matter of handling the error more gracefully

**Comment by athosbr99** [comment]
I have been using this OS for a while, changed a theme or two, but it is default in the sense that I downloaded the ISO on kubuntu.org and installed it as is.

I also faced this issue while using Manjaro with KDE on Visual Studio Code, but I didn't looked for a fix at that time.

**Comment by hpoul** [comment]
Can you try the latest version (1.7.1), it should handle errors more gracefully. But gnome-keyring or ksecretsserviced is still required for cloud storage.
Do you still experience Clipboard Request Failed messages?

**Comment by athosbr99** [comment]
My install seems to be on build 1.7.1+1324. The error on startup still happens, but the second one doesn't happen anymore on typing keystrokes or copying password.

**Comment by YourFriendCaspian** [comment]
I get the same error with both the current snap package and the current tar package on Manjaro KDE.

**Comment by hpoul** [comment]
@YourFriendCaspian which one, regarding the secrets service, or the clipboard?

**Comment by YourFriendCaspian** [comment]
@hpoul Oh sorry, the secret one.

**Comment by hpoul** [comment]
@YourFriendCaspian do you have gnome-keyring or ksecretsserviced installed? is the **exact same** error message?

**Comment by athosbr99** [comment]
In the meantime I ended up switching distros and the DE. I am now using Manjaro with Gnome.

I just installed the app from snap and did a quick test, including login with Dropbox and no errors were shown to me.

Since @YourFriendCaspian is also using Manjaro, but with KDE (which I was using when I opened this issue), I assume this is being cause by some problem in the implementation of the secret service in KDE.

**Comment by hpoul** [comment]
@athosbr99 thanks for the heads up. great to hear that it's working in gnome. I guess the problem comes down to gnome-keyring vs. ksecretservice (just guessing here, as i'm not a linux user nowadays)
@YourFriendCaspian maybe you can post your exact error message there was [also a report that the "login" collection](https://github.com/authpass/authpass/issues/112#issuecomment-660500080) was simply not created by default. which i think can be solved by following https://github.com/zalando/go-keyring#linux to create it, or https://unix.stackexchange.com/a/295652/284346
