### ISSUE TITLE
Password view suggestions (iOS)

### ISSUE THREAD

**Issue by eL-Prova** [authpass/authpass#109]
Hi focks,

Because of the endlife of MiniKeePass I was searching for an other tool and found this one.
It works well and active community is very nice :-)

I want to make an suggestion for iOS (I have no idea if this also effects Android) but the passwords are very hard to read.
Based on my experience of MiniKeePass I expect that I can view an item first before edit it. When I enter an records I dont see the password (no problem :-) ) but when I want to show the password I hit on the input, but my keyboard is popping up and my password is hidden behind the keyboard. So in that case I hit outside the textbox and the keyboard hide, now I can view the password.

Suggestion 1: Add an pencil or something to make the possibility to change otherwise its read modus
Suggestion 2: Use an other font for the passwords. The uppercase of i ("I") is tough to read from the lowercase l ("L")
Suggestion 3: Most of the time I read passwords, so similar to MiniKeePass show an popup with the password bigger in the screen.

Kind regards and keep up the good work :-)

**Comment by hpoul** [comment]
I very much appreciate UI suggestions, and I also think that it's something worth improving (the Edit UI is basically still a very first revision, so I know it's far from perfect). just one thing to keep in mind: I do not intend AuthPass to be a clone of MiniKeePass, so just because MiniKeePass has something, and you are used to it and hence think every password manager app should work that way, is not a valid reason that it's superior :-)

the two things that seem to be on top of MiniKeePass users mind are hierarchical password lists and a dedicated edit mode :-) I'm completely against the first.. the second one i'm not sure ;) I honestly think that this is just a matter of taste and what you are used to.

suggestion 2/3) is this basically the "Reveal" mode i've shown in the other issue? It also uses another font.

**Comment by wallzero** [comment]
I also suggest the password reveal use a different font. My case just a couple hours ago was having trouble distinguishing a zero `0` from a capital `O`.

**Comment by hpoul** [comment]
@wallzero i see no such problem in the password present. The reveal users the default font, which is correct.

![Screenshot_20211004-120208_AuthPass](https://user-images.githubusercontent.com/313066/135832375-a30091ed-d48c-4dd7-9fae-e33211663473.jpg)
