### ISSUE TITLE
IOS - Enable file sharing to allow copying/deleting of local .kdbx files for use with Authpass

### ISSUE THREAD

**Issue by BuongiornoTexas** [authpass/authpass#110]
Hi, 

My use case is as follows:

- I use Keepass/KeepassXC on the desktop.
- I use MiniKeepass on IOS. 

I can't use cloud solutions, so I keep password files in sync by periodic manual copying using iTunes file sharing. (This works fine as I don't update/change my password files all that frequently). This approach works with MiniKeepass and Strongbox.

With MiniKeepass on the way out, I'd like to switch to AuthPass. However, I can't see a way to use file sharing to copy a .kdbx file from my desktop to IOS Authpass. (Unless I'm missing a trick here - in which case, can anyone tell me what I should be doing to get this to work?).

Cheers,

Larry

**Comment by hpoul** [comment]
To be honest, I haven't heard about that file sharing before.. i'll check it out..
But iOS also has a `Files` app nowadays, can't you just copy the file to any location on your device and open it from there?

**Comment by hpoul** [comment]
Okay, the actual file sharing seems to be pretty simple: https://developer.apple.com/documentation/bundleresources/information_property_list/uifilesharingenabled .. the problem is that we would have to come up with a way to browse through the Apps `Documents/` folder, there is no such UI currently :-/
But sounds useful nevertheless, right now the only way to find internally created password files is through the 'Recently opened' files.

**Comment by BuongiornoTexas** [comment]
> But iOS also has a `Files` app nowadays,  can't you just copy the file to any location on your device and open it from there?

Unfortunately the Files app is not available on IOS 9 (which is where I'm stuck for a while). I also put a .kdbx file into the documents folder of another application (Goodreader) and then tried to open it as a local file from Authpass - However, this dropped me straight into the icloud/idrive folders (I assume this is what is meant to happen). 

>  the problem is that we would have to come up with a way to browse through the Apps `Documents/`, there is no such UI currently :-/ But sounds useful nevertheless, right now the only way to find internally created password files is through the 'Recently opened' files.

Fair enough. However, the use of this document sharing capability has been a long standing way for transferring files in the IOS ecosystem (I think I've been using it for a decade or so for a variety of apps). Is there a possibility to change the target directory for internally created files to the `Documents` directory for IOS? If so, could this allow maintenance of the existing structure and file sharing to coexist?

Regardless, thanks for the good work you are doing with Authpass!

Cheers,

Larry

**Comment by hpoul** [comment]
fyi, I've now finally implemented this.. so it will be possible to copy kdbx files directly into the app using iTunes/Finder:

<img width="642" alt="Screenshot 2020-08-24 at 16 12 52" src="https://user-images.githubusercontent.com/313066/91055256-b2ba8200-e624-11ea-9e23-dd26341250cb.png">

available in the next release (probably 1.7.5 in a few days)

**Comment by BuongiornoTexas** [comment]
Excellent - thanks very much for doing this!

**Comment by hpoul** [comment]
1.7.5 is now rolling out. For existing "internal" files (which were created inside AuthPass) you'd have to open them once so they are moved to the new documents location. Otherwise it is now possible to see the folder in itunes/finder. Once it contains .kdbx files (file extension is important) clicking on 'Open Local File' will give a choice between 'Internal file' and 'File Picker'. (Internal files are those in the apps documents folder, file picker is using the iOS file picker)

![IMG_BC33B2AAFBA5-1](https://user-images.githubusercontent.com/313066/91421343-1d063900-e856-11ea-9264-7d1ef1c87b7c.jpeg)

I should probably start writing documentation about those things 🙈️ anyway, let me know if this works for you.

**Comment by BuongiornoTexas** [comment]
@hpoul Thanks very much! It is working as expected. Now I have to spend a bit time figuring out the interface.

**Comment by hpoul** [comment]
@BuongiornoTexas great, thanks for giving it a try and reporting back. If you've got problems figuring out the UI, don't hesitate to get in contact. At the very least it would help to know what documentation to create :-) (either here, email support inside the app, or [discord channel](https://authpass.app/go/discord) ;-) )
