### ISSUE TITLE
Local WebDav Server Connection Unauthorized 

### ISSUE THREAD

**Issue by SabariVig** [authpass/authpass#112]
Unable to connect to local webdav server 
. getting 401 unauthorized 

Tried with android and linux.

```
flutter: 2020-07-18 13:35:12.690963 SEVERE authpass.google_drive_ui - Error while authenticating.###
StorageException{type: StorageExceptionType.authentication, details: Provided credentials were invalid. (Server Response 401, errorBody: null}
#0      WebDavProvider._expectSuccessResponse (package:authpass/cloud_storage/webdav/webdav_provider.dart:243)
#1      WebDavProvider.propFind (package:authpass/cloud_storage/webdav/webdav_provider.dart:142)
<asynchronous suspension>
```

For Testing Used https://github.com/BytemarkHosting/docker-webdav

**Comment by hpoul** [comment]
Thanks for the report.
Did you configure digest or basic authentication? AuthPass currently only supports basic authentication for webdav.

**Comment by SabariVig** [comment]
Just Tried On Basic Auth 

![image](https://user-images.githubusercontent.com/33371586/87849112-a34c6880-c903-11ea-845a-86be66cc8ef5.png)

**Comment by hpoul** [comment]
can you try on android? the secret store on linux is implemented, but not yet released (either today or tomorrow)

**Comment by SabariVig** [comment]
Yeah it works 👍

**Comment by hpoul** [comment]
I've just pushed a beta version to snapcraft, maybe you can give this one a try?

```
sudo snap install authpass --beta
```

(1.7.0+1318)

I've now also added support for digest authentication.

**Comment by SabariVig** [comment]
Oh I  used the manual installation I don't use Ubuntu derivatives

**Comment by hpoul** [comment]
ah okay, no problem the tar.gz is also available: https://data.authpass.app/data/artifacts/authpass-linux-1.7.0_1320.tar.gz

btw. how do you usually install/discover desktop software on linux? i've thought about using app images or a custom deb/rpm repository.. but not sure if that would be used by anyone :)
otherwise I would have to find a way to provide an update mechanism..

**Comment by SabariVig** [comment]
Thank You for this amazing project. I usually search AUR(Or any default package manager of the OS) first. then i try to find binaries. Appimages are also fine but its tedious to maintain .And i dont prefer snap

As for the new release I'm getting this error 

![image](https://user-images.githubusercontent.com/33371586/87855310-06a2be80-c935-11ea-91f5-42a9d824c24f.png)

**Comment by hpoul** [comment]
For cloud storage some form of secret store is required, otherwise you would have to enter this on every launch.. Which is not yet supported unfortunately..
Can you install some secret service implementation? https://specifications.freedesktop.org/secret-service/latest/ 
Either gnome-keyring and ksecretservice should work

**Comment by SabariVig** [comment]
The Login seemed to work after installing  gnome-keyring but again WebDAV is not 
![image](https://user-images.githubusercontent.com/33371586/87856162-ccd4b680-c93a-11ea-8b6f-0ba459d5a979.png)

**Comment by hpoul** [comment]
have you tried something like https://unix.stackexchange.com/a/295652/284346 ? another thing i found was: https://github.com/zalando/go-keyring#linux
