### ISSUE TITLE
F-Droid can't find new updates

### ISSUE THREAD

**Issue by licaon-kter** [authpass/authpass#118]
...since https://authpass.app/data/fdroid-version.txt is not updated

**Comment by hpoul** [comment]
@licaon-kter as far as i have seen the current version can't compile because i have been using a new flutter version.. i wanted to wait until flutter beta released to stable to submit a MR.. 
It would be really nice if it was possible to update srclibs through the update checker.. I try to keep pretty up to date with flutter and regularly use beta or even dev releases..

**Comment by licaon-kter** [comment]
Right, well, yes we don't have this (afaik)

Any timeline or we should switch to a (hopefully tagged) beta of sorts?

**Comment by licaon-kter** [comment]
/closing in favor of https://github.com/authpass/authpass/issues/120
