### ISSUE TITLE
[UI] Bad color when right swiping to copy the username

### ISSUE THREAD

**Issue by libalis** [authpass/authpass#210]
(Testen on Android 10 with Authpass 1.7.10+1612 and dark mode)
When swiping right to copy the username a very bright yellow color is used the background.
Not only is this creates this a very bad contrast to the white font, but also it doens not fit with the color palett at all.
Switching the color to green or something similar would help a lot in my opinion.
Otherwise, thank you very much for the effort put into this amazing project.
Keep it up.

**Comment by hpoul** [comment]
thanks for the report, and sorry for the late reply. This will be fixed in the next version (>=1.9.1)

<img width="400" alt="Screen Shot 2021-08-03 at 23 48 57" src="https://user-images.githubusercontent.com/313066/128091017-1672906f-3c24-4965-8fbf-77366f6eda11.png">

<img width="347" alt="Screen Shot 2021-08-03 at 23 49 46" src="https://user-images.githubusercontent.com/313066/128091026-1a128dba-2ff7-49a3-98ce-c48c4dc5feb6.png">
