### ISSUE TITLE
Authpass on Android not filling passwords in brave browser

### ISSUE THREAD

**Issue by christopherpickering** [authpass/authpass#217]
When using Brave browser Authpass is not asking to populate password fields.

* On Android Galaxy s10e  v Android 10
* Set Autofill service to Authpass
* Added password for website
* Password list is unlocked
* Open Brave browser v1.19.92, chromium 88.0.4324.152
* Attempt to login
* Nothing recommended :(

It worked with LastPass, so I'm not sure what is different here?

![Screenshot_20210213-094515_Brave](https://user-images.githubusercontent.com/17788706/107854248-53257e00-6de0-11eb-8204-671bc0c28405.jpg)

**Comment by hpoul** [comment]
Doing a quick google search it looks like brave browser does not support the android autofill api: https://community.brave.com/t/android-autofill-api-enabled-in-brave/64238
(afaik LastPass uses the old way of using the accessibility features to overlay onto other apps, which AuthPass does not support) So maybe you can check if brave browser has since implemented autofill api, which from the forum post does not look like it.

**Comment by christopherpickering** [comment]
Thanks, forgot to post back - I changed to duckduckgo browser and it works. 

Hopefully Brave pics that up one day!
