### ISSUE TITLE
Difficulty building for linux, "couldn't find pubspec.yaml in kdbx.dart"

### ISSUE THREAD

**Issue by makoConstruct** [authpass/authpass#225]
Attempting to build the flutter app in `/authpass`

```
» flutter config --enable-linux-desktop
Setting "enable-linux-desktop" value to "true".

You may need to restart any open editors for them to read new settings.
» flutter build linux
Could not find a file named "pubspec.yaml" in "/home/mako/programming/toying/authpass/deps/kdbx.dart".
Running "flutter pub get" in authpass...                                
pub get failed (66; Could not find a file named "pubspec.yaml" in "/home/mako/programming/toying/authpass/deps/kdbx.dart".)
```

If there is something in `_tools` I'm supposed to be using, I can't tell what.

**Comment by hpoul** [comment]
Did you follow the steos in `CONTRIBUTING.MD` (ie clone submodules)

**Comment by makoConstruct** [comment]
Further problems:

Step 4 says `git clone https://github.com/authpass/authpass.git`, but this was already done in step 2. Is this intentional?

Build fails before building the linux version.

```
» flutter run -t lib/env/development.dart
"ar": 191 untranslated message(s).
"de": 6 untranslated message(s).
"et": 191 untranslated message(s).
"fi": 191 untranslated message(s).
"fr": 13 untranslated message(s).
"he": 8 untranslated message(s).
"id": 7 untranslated message(s).
"it": 9 untranslated message(s).
"lt": 87 untranslated message(s).
"pa": 189 untranslated message(s).
"pl": 56 untranslated message(s).
"pt": 191 untranslated message(s).
"pt_BR": 8 untranslated message(s).
"ru": 131 untranslated message(s).
"sk": 8 untranslated message(s).
"tr": 115 untranslated message(s).
"uk": 80 untranslated message(s).
"zh_TW": 7 untranslated message(s).
To see a detailed report, use the untranslated-messages-file 
option in the l10n.yaml file:
untranslated-messages-file: desiredFileName.txt
<other option>: <other selection> 


This will generate a JSON format file containing all messages that 
need to be translated.
Launching lib/env/development.dart on SM G960U in debug mode...
ndkVersion: 21.0.6113669                                                
secrets not found at /home/mako/programming/toying/authpass/authpass/_tools/secrets/gradle_home/gradle.properties
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                       265.9s
Exception: Unsupported Android Plugin version: 4.1.2.
```

(this is the second time I've run the build)

**Comment by hpoul** [comment]
sorry for the late reply

> Step 4 says `git clone https://github.com/authpass/authpass.git`, but this was already done in step 2. Is this intentional?

well, kind of.. it just to illustrate that if you use `cd authpass/authpass` the first `authpass` is the name of the cloned repository.. and `authpass` the subdirectory inside that clone. That's why I reiterated the `git clone` command.

> 
> Build fails before building the linux version.
> 
> ```
> Running Gradle task 'assembleDebug'...                                  
> Running Gradle task 'assembleDebug'... Done                       265.9s
> Exception: Unsupported Android Plugin version: 4.1.2.
> ```
> 

This looks like you are trying to build the android version, not the linux version.. for the linux version you would have to first enable desktop support via `flutter config --enable-linux-desktop` and then use `flutter run -d linux -t lib/env/development.dart` see also https://flutter.dev/desktop#from-the-command-line

I'll close the issue for now.. feel free to comment if you still encounter problems. (make sure to update flutter to the latest dev channel and the repository)
