### ISSUE TITLE
[UI] Distinction between hamburger menu function and three dot menu function unclear

### ISSUE THREAD

**Issue by tiborrr** [authpass/authpass#232]
Problem:
In all versions of Authpass, I found that I have trouble choosing the right menu button for opening settings. I always get confused between the two. Anyone else experiencing this?
![image](https://user-images.githubusercontent.com/16014746/123055481-3b04e180-d406-11eb-9a88-82c77a778359.png)

Solution:
Change the hamburger menu to a filter icon as that is what the function does. This also means you can remove combine the filter and hamburger menu.
https://api.flutter.dev/flutter/material/Icons/filter_alt_rounded-constant.html

**Comment by hpoul** [comment]
I disagree regarding changing the burger menu to a filter icon. imo it is pretty much established that the app drawer can be used for changing categories. Take for example the Gmail App, which works exactly the same way. Especially since the filter icon is already used in your screenshot, having it there twice wouldn't make things easier either.
