### ISSUE TITLE
AuthPass 1.9.6+1904 (Apple Store, Apple M1 Max) does not download favicons for new entries

### ISSUE THREAD

**Issue by minimondo** [authpass/authpass#312]
I imported my database from KeePassXC; all the prior favicons are intact.

I have ticked the box to download favicons automatically, in Preferences.

For every new entry in AuthPass, the favicons are NOT downloaded. There seems to be no way to manually force such downloads, unlike KeePassXC.

I regard this as a major UI issue.

**Comment by hpoul** [comment]
Can you give an example of an entry where the icons are missing? maybe a screenshot once you removed anything personal..

fwiw, unlike other clients (not sure about KeePassXC) the favicons in AuthPass are purely cosmetic.. they aren't "downloaded" and stored into the keepass file, they are just shown on-demand. that's why there is no way to manually "force downloads".. as simply scrolling to the entry should download it..

**Comment by minimondo** [comment]
Thanks for your prompt response. First, I was wrong - only _some_ websites don't result in downloaded favicons (I have identified one such site in the screenshot attached). I can't find the other website yet (I have a large database).

The website(s) do have favicons (which KeePassXC can download, for example).

The favicons being "cosmetic" is not a problem for me at all.

I'd be grateful if you could test/replicate the issue for this website (https://www.macquarie.com.au).

Thanks!
![AUTHPASS](https://user-images.githubusercontent.com/139458/175757120-f7a93c3e-b971-4160-9ae5-361b25fab5df.jpg)

**Comment by hpoul** [comment]
the server didn't support 8 bit favicons .. I've updated a few dependencies and it seems to work now. If you have any further websites without images (which actually have favicons) feel free to open a new issue.. 

<img width="377" alt="Screen Shot 2022-06-25 at 09 14 11" src="https://user-images.githubusercontent.com/313066/175762959-825efdc6-7972-42fa-8d34-8a8eaa42b981.png">
