### ISSUE TITLE
No support for Smart Cards

### ISSUE THREAD

**Issue by isaaclepes** [authpass/authpass#349]
My database file is secured using a Yubikey, but this app does not appear to support smart cards. It would be a great feature to add, but I didn't want to create a whole new account just suggest on the forums.

**Comment by KiARC** [comment]
I was about to to create an issue for this. From the opposite perspective, I currently use Authpass and am considering buying a Yubikey, but Authpass doesn't seem to support them, which is really unfortunate.

**Comment by hpoul** [comment]
Closing this due to duplicate.. see https://github.com/authpass/authpass/issues/176#issuecomment-703128870

Imho it makes not too much sense to have yubikey support in a client side application.. i think the security would be identical to storing a secret file on a usb drive.. i don't see how a yubikey adds anything.. when used for authentication in a client/server application it solves the problem of repeatability if the secret would be exposed in network traffic.. 
the documentation from keepassxc is also pretty funny: https://keepassxc.org/docs/#faq-yubikey-no-extra-file

> which resembles actual two-factor authentication more closely

🤣 "resembles" in a security context is not really helpful usually .. as it looks like being safe without providing any actual security..
