### ISSUE TITLE
Missing authentication for subsequent WebDAV requests

### ISSUE THREAD

**Issue by TheLastZombie** [authpass/authpass#379]
**Describe the bug**

My KeePass database file is located on a WebDAV server, which is only accessible with authentication. When I first select *Load from ...* > *Load from WebDAV* in the app and enter my credentials, everything works fine; I'm able to browse the files on the server and navigate to and select my KDBX file. Unlocking the database works too, and I can then see its entries in the app.

However, after closing and re-opening the app (or anything that triggers a redownload of the database for synchronization), I get the following error:

```
Unexpected Error: LoadFileException{message: Error while loading file from webdav server. Unexpected error code: 403}
```

**To Reproduce**

*(see above)*

**Expected behavior**

I expected the database file to be downloaded successfully.

**Screenshots**

N/A

**Desktop (please complete the following information):**

N/A

**Smartphone (please complete the following information):**

 - Device: Google Pixel 8 Pro
 - OS: GrapheneOS 2024080600
 - Browser: N/A (Android application)
 - Version: 1.9.10 via F-Droid, 1.9.11 via GitHub release

**Additional context**

I started `netcat` to inspect the request sent to the server:

```HTTP
GET /path/to/database.kdbx HTTP/1.1
Host: my.domain.com
User-Agent: Dart/3.2 (dart:io)
Accept-Encoding: gzip
```

I noticed the request is missing the authentication header(s), making the server return a 403 error.

This happens whether *Save Password with biometric key store?* is enabled or not.

**Comment by 9001** [comment]
I can confirm that this was a copyparty bug; it would respond with a 403 instead of a 401, which is the response that AuthPass (and many other WebDAV clients) require before they are willing to send credentials. Hard to please both graphical browsers and WebDAV clients at once :-) but copyparty v1.16.3 should get it right.

just in case anyone bumps into this comment and decides to give copyparty a try, please be aware that you must give your user the permissions `rwd` (read/write/delete), and the option `daw` must be enabled to permit WebDAV's upload behavior (either globally or just for the volume you keep the AuthPass-db). This is because copyparty normally prevents overwriting existing files by giving them new filenames, which is usually a good idea to avoid accidentally losing files. But AuthPass seamlessly replacing the old AuthPass-db with a new version is exactly what we want in this case.
