### ISSUE TITLE
Add support for showing groups

### ISSUE THREAD

**Issue by hpoul** [authpass/authpass#44]
Allow users to group entries - kdbx library should already support it. So it's just a matter of allowing users to select a group for an entry and representing it in the UI.

See also discussion about use case: https://www.reddit.com/r/privacy/comments/dc8n7k/authpass_keepass_client/f3p016p?utm_source=share&utm_medium=web2x

**Comment by hpoul** [comment]
first version implemented, missing:

- [ ] Sort groups alphabetical (for now)
- [ ] If there are unnamed groups, add a place holder name (the same for database names)
- [ ] If the user has only one database (file) open, (maybe) skip this step altogether.

**Comment by abawany** [comment]
On iOS with the latest version, I still see all of the entries as a flat list, including the ones in the 'Recycle Bin'. Is it possible to display the entries in their respective categories pls?

**Comment by hpoul** [comment]
@abawany well, do you have an idea how to best integrate it into the current  app? because I personally really like having a flat list, because i'm to lazy to organize my  passwords into group and simply search through everything. Group hierarchy just sounds a bit old school to me from a time without search :-) I guess i'll just add a second view (maybe via two different tabs, or a settings option) to switch between flat list and hierarchical groups.. but i'm still not convinced a hierarchical  view is advantageous vs a flat list for the typical use case..

(the only thing obviously would be to by default filter out items in the trash..)

**Comment by abawany** [comment]
@hpoul I agree that I came to like the flat list as well; I was used to the other keepass managers showing by groups but I adapted. If you are able to allow filtering by groups or just filter out 'Recycle Bin' entries, I would be happy.

**Comment by hpoul** [comment]
@abawany i certainly agree with the recycle bin ;) can you give a few more details how you'd like the "filter by groups" to work - technically you can already filter by group (in the action bar there is a "Sitemap" icon), but the usability is terrible :)
would you like to configure predefined set of groups you can show/hide together? or just manually switch between groups?
out of curiosity.. how many groups are you using?

**Comment by abawany** [comment]
@hpoul I am not a good usability expert but my implementation would comprise of listing the groups along with checkboxes plus options for 'select all' and 'deselect all'; groups thus selected would have their entries displayed. 

I use two different kdbx files (work and personal) and each has around 8 groups each with multiple entries within each. You can imagine that a flat view is overwhelming for this scenario and I work around it by closing one of the two files as required.

I tried the filter-by-group functionality and I now understand it: clicking the group name filters by just that group whereas clicking the right arrow goes one level deeper in this hierarchy. I was initially confused by its function since I kept clicking the right arrow and didn't realize that clicking the actual group name acted as a filter. I see what you intended there and if I rearranged my kdbx files to have just one group each (work, personal), then I could just view the entries for that kdbx.

In retrospect, I realize that my feedback comes from being used to the old model of Keepass with groups and it has led me to expect a more confusing hierarchy model than your software is encouraging. I am encouraged to refactor my file to have more consolidation and fewer groups but for people who are not willing to make changes to their password file, perhaps filtering by multiple groups or just filtering out 'Recycle Bin' would help improve adoption. Thanks again for your hard work on this project and for the usability insight I have gained from this discussion.

**Comment by hpoul** [comment]
@abawany i actually quite like the checkbox-idea.. the only problem imho is the hierarchical nature of groups.. because for checkboxes everything would have to fit on one  screen.. but most treeview designs would limit the depth of the groups before it becomes unusable..

I could think of two possible solutions.. either have the "indent" of the tree only like 2-4 pixels, but with a distinct color for each hierarchy.. or do not indent the child groups, but add a "backcrumbs" below each of the items. maybe i'll try something like that..

but regarding the filter: yes, i assumed that the tapping on the list item vs. arrow is not really a usability hightlight :-) but technically every file has implicitly it's own root group, so i think you should be able to show only one of your open files through that filter?

**Comment by abawany** [comment]
@hpoul True re. hierarchies - the backcrumbs approach similar to the current filtering-by-group approach might work well

Re. tapping the list item vs. arrow, now that I've discovered it, I quite like it :) - the discoverability was the issue for me. It's a good idea to filter by root groups to enable easier browsing of multiple kdbx files vs. closing/opening. 

Thank you for your excellent work and for helping me better understand the product.

**Comment by hpoul** [comment]
fyi, i have now at least implemented that by default deleted items (ie. recycle bin) is hidden.. I still kept the current group list UI, but it should be easy to extend later with a checkbox UI..

btw. if i understand it correctly the filter by (root) group should work for your use case of using filter instead of closing/opening files?

**Comment by abawany** [comment]
I look forward to the getting the update and trying out v1.5.7 - the recycle bin filtering will address a large proportion of my initial concerns.

I can also confirm that the filter-by-root-group works well for me and is vastly more convenient than closing/opening files. Thank you for suggesting this very convenient option.

**Comment by hpoul** [comment]
I have now implemented the checkbox-style filter - the old dialog is still available via the overflow menu "Manage Groups".. I'm still not really happy with the look and feel, and it's still a lot of taps.. but i think it's a bit more understandable what happens before tapping :)

![2020-05-13 11-58-36 2020-05-13 12_00_29](https://user-images.githubusercontent.com/313066/81799390-941afa00-9511-11ea-9ca2-f4284f6ccddb.gif)

**Comment by hpoul** [comment]
btw. the color of the indentations (and icons) depends on the selected file color.. i should probably choose some nicer colors by default when opening files :-)

<img width="250" alt="Screenshot 2020-05-13 at 12 03 59" src="https://user-images.githubusercontent.com/313066/81799684-fe339f00-9511-11ea-9529-067441afaa0f.png">

**Comment by hpoul** [comment]
I have now [released 1.6 with this being the "default" group filter ui](https://authpass.app/articles/filter-by-groups-file-attachments-for-passwords-authpass-1.6/). so i resolve this issue for now, if there are any remaining issues feel free to create a new issue :-)

**Comment by abawany** [comment]
Thank you @hpoul  - I look forward to trying it when I update to 1.6 .
