### ISSUE TITLE
The getter 'bytes' was called on null.

### ISSUE THREAD

**Issue by roymckenzie** [authpass/authpass#52]
I am unable to open a keepass database on Android 9, AuthPass version 1.3.0+115. I have used KeePassXC on Linux to save the database. I have also used NextCloud Keeweb to export the database. They both export them in Keepass 2 format. I am getting the same error that was mentioned below

> ...I get this error when I try to decrypt the database:
> 
> "Unknown error while trying to open file. NoSuchMethodError: The getter 'bytes' was called on null.
> Receiver: null
> Tried calling: bytes"

_Originally posted by @northorsouth in https://github.com/authpass/authpass/issues/48#issuecomment-548091447_

**Comment by hpoul** [comment]
This very much sounds like you are saving in kdbx 4 format. In KeepassXC you can select Database -> Database settings ... Security ... Encryption Settings ... and use `kdbx 3.1` instead of kdbx 4.

<img width="583" alt="Screenshot 2020-01-30 at 22 30 01" src="https://user-images.githubusercontent.com/313066/73492012-20187400-43b0-11ea-8c8c-cc124d27dfa3.png">

Please verify that it is saving in kdbx 3.1 format. AuthPass does not (yet) support kdbx 4.x (because there is no dart implementation for argon 2 and dart:ffi support (native C interop) is still in a very early phase for dart/flutter)

**Comment by hpoul** [comment]
@roymckenzie have you tried with kdbx 3.1? In the latest version i have also improved the error message so you should see if you are using an unsupported kdbx file version>

**Comment by roymckenzie** [comment]
Thank you!

**Comment by hpoul** [comment]
fyi authpass now supports kdbx 4.x so this problem should be resolved in the latest version (1.5.2)
