### ISSUE TITLE
Dark theme for Android 

### ISSUE THREAD

**Issue by GreyMarvel** [authpass/authpass#55]
Hi, 

I am seriously impressed with your app , I've only just discovered it on Fdroid . I've been looking for an opensource option to sync my passwords between devices using Nextcloud with little success, until now! 
I  cant wait till the Linux client is available .
I do however think that it should be explained on the readme how to find the WebDav URL needed to access Nextcloud or similar cloud solutions, or at least an example of what it might look like. 

I had to look at the Gnome nextcloud webdav file sync application  on Linux mint  to find  the exact URL  it was similar to 
https://myServersName.duckdns.org/remote.php/webdav/pathToMyFile

anyway, I've digressed  would it be possible to have a dark theme in the android app.

thanks again for such a great app .

**Comment by hpoul** [comment]
hi, glad you find AuthPass useful ;-) You are probably right re. documentation.. i've created another issue for creating documentation https://github.com/authpass/authpass/issues/56

hmm.. dark theme shouldn't be too hard to implement.. you mean the android 10 dark mode, right?

**Comment by GreyMarvel** [comment]
Currently I am on android 9 but if android 10 is the way to go then so be it but yeah whatever dark theme/mode is an option . I know alot of apps now include a dark theme even the latest nextcloud android client has a dark theme option .

Also do you have a (monetary) donation  option for your app ?

**Comment by hpoul** [comment]
okay sure, i'm just asking because since android 10 it would be simply taken from the system preferences, but i guess it would make sense to add a app specific setting anyway.. :-)

> Also do you have a (monetary) donation option for your app ?

not right now, it's still a bit early for AuthPass i guess ;) do you have experience with any options? I'd guess paypal/btc would be the easiest, and doesn't add too much (any) fees, but things like open collective or github sponsors might add additional incentives?

**Comment by GreyMarvel** [comment]
Oh I didn't know that about android 10, I wish I was on android 10 now but I appear to be stuck on 9 for the foreseeable future . Honestly I haven't had many dealings with alternatives to PayPal but I have seen other projects use librepay . I believe that fdroid use librepay for all payment to individual apps , but I don't know much about it .

**Comment by hpoul** [comment]
I've now created a very first version of a dark mode.. actually had to change a few more colors than i've thought.. but not too bad.. i'll probably release a new version in the coming days.. (it should work on all platforms equally) - although fdroid will take quite a bit longer probably, because i require a new flutter version which is not yet stable and i'm not sure if fdroid supports that..

![Screen Recording 2020-02-12 at 11 58 08 2020-02-12 12_00_49](https://user-images.githubusercontent.com/313066/74329077-6a75f980-4d8f-11ea-8fb3-5931b425d84d.gif)

**Comment by GreyMarvel** [comment]
Wow that was quick and it looks great . I don't mind waiting for fdroid to support it.
 Thanks for the quick work .

**Comment by hpoul** [comment]
Hey, I have now released a version on the google play store.. do you mind switching from the fdroid version to the play store? (it's the same thing, just with dropbox/google drive support also enabled :-) ) https://play.google.com/store/apps/details?id=design.codeux.authpass

for fdroid i'd have to send a PR to their data repository and see how to get flutter beta version working..

btw, I have now registered (and just got accepted) for GitHub Sponsors, if you're interested ;-) So there is a `Sponsor` button on the top of the GitHub page.

**Comment by GreyMarvel** [comment]
I don't mind  giving  the Google play version a try for awhile until it becomes available on fdroid. Especially if it give me access to the new dark theme. 
That's brilliant ! I shall get round to donating to your project. Thanks so much for you app and you quick resolve to this issue.

**Comment by hpoul** [comment]
Great, thanks :-) let me know if it works for you, and if you find any missing dark theme changes :-) Only problem i found right now was white text in the progress dialog.. i'll fix that, otherwise i'd close this issue

**Comment by GreyMarvel** [comment]
It looks great! I haven't seen any obvious dark theme errors .

I also dropped you a little donation through the sponsor tab, to go towards  further development of the app .

Thanks again for this . I happy for you to close this issue

**Comment by hpoul** [comment]
@GreyMarvel thanks, very much appreciated :-D if you have any further suggestions just let me know or add a new issue. and if you've got a minute you could give the app a rating ;) it's a bit negative right now, because it seems everybody needs kdbx 4 support 🤷‍♂️although it shouldn't be too long before that's also resolved ;)
