### ISSUE TITLE
Support to show custom icons

### ISSUE THREAD

**Issue by TobiasDev** [authpass/authpass#68]
In KeePassXC (which is what I currently use on Windows and Linux until Authpass arrives since the design is terrible), you can add custom icons for all your entires (or download fav-icons). When I open the database on my phone in AuthPass I get a key icon. Are you planning on adding support for custom icons in AuthPass at some point? 

![grafik](https://user-images.githubusercontent.com/5912371/81822627-a9088500-9533-11ea-97e2-4e19d9dfbf3f.png)

**Comment by hpoul** [comment]
Right now only [predefined icons](https://github.com/authpass/kdbx.dart/blob/master/lib/src/kdbx_consts.dart) are supported. tbh I didn't think anyone would use custom icons :-)
Shouldn't be too hard to support them though..

favicons for each service are a bit different..  I guess it would make sense to download them on-demand, rather than storing them in the kdbx file. (I'm trying to keep those files as small as possible).

btw. do you enter a nice "Website" field for every service? I personally just enter the rough domain name as "title" and never mind the "Website" field ;-)

**Comment by TobiasDev** [comment]
Of-course I use the website field. :D Otherwise the auto-fill on the Firefox plugin don't work. I'm lazy, so I want it to be as easy and fast as possible to log into websites. :D Though not lazy enough to use something like Bitwarden since I still want to have my "own" password file. 

Also, I believe that favicons are downloaded and added to the file in KeePassXC. Then they act like any other custom icon I add myself. :) I mostly use Custom Icons since A. They are ugly as hell in KeePassXC, I love the software and such, but that UI is very Windows XP and B. It's a lot easier on a quick glance to see what is to what. Sometimes I have several logins for the same webpage. E.G. Personal usage, company usages, etc. Then I use a custom icon with different BG colors to quickly see which one I need. :)

**Comment by TobiasDev** [comment]
I should probably mention that I care a lot about the UI of my apps. I have changed from one app to something not as good JUST to get better UI. :D I only use apps with terrible UI if I really can't find another app that is even close to the functionallity. Like in the case with KeePassXC currently on Windows.

**Comment by hpoul** [comment]
fyi, I have now implemented **showing** of custom icons (not changing).. but i'm not quite sure this improves the UI, because the favicons added by keepassxc are of pretty bad quality:

<img width="386" alt="Screenshot 2020-08-13 at 13 12 32" src="https://user-images.githubusercontent.com/313066/90128254-e36a0400-dd66-11ea-97b9-ffa7cc809162.png">

in the above screenshot they are scaled up, if i don't scale them up, they don't look much better:

<img width="366" alt="Screenshot 2020-08-13 at 13 13 29" src="https://user-images.githubusercontent.com/313066/90128292-f5e43d80-dd66-11ea-834b-a95a9e881817.png">

I did not yet add support for changing custom icons. I honestly think it would be nicer to fetch the icons from the internet in a better quality. But this would involve some magic if the user does not have complete, valid URLs in their 'Website'(`URL`) field.

**Comment by TobiasDev** [comment]
Hmm, there you are correct. :( I thought the grabbed them in higher quality, but apperently not. :(

**Comment by hpoul** [comment]
I've now played around a bit to dynamically load the icons.. I actually quite like it.. but I still have to solve a few usability problems.. like when a user still wants to change the icon.. or when I was not able to load the correct icon..

<img width="912" alt="Screenshot 2020-08-15 at 12 29 00" src="https://user-images.githubusercontent.com/313066/90310597-47213800-def3-11ea-8079-6fda9433e69a.png">

I'm also not yet completely sure about the privacy/security implications. The 'Website' domains (not the full URL, just scheme + host) are sent to my server and [i use some magic](https://github.com/authpass/authpass-cloud/blob/d0171ef81e2cf52c2bb48c31f9f34d73a143b866/packages/authpass_cloud_backend/lib/src/companyimage/besticon.dart#L93-L123) to find a good icon/logo.

I almost think the most sensible thing would be to make it a kdbx-file based option.. so when opening an existing kdbx file, it is turned off by default, but for new users I can add a hint in the 'Website' field.. but the most private thing this would leak are internal host names if someone adds a private intranet domain.. i hope noone uses that field to store passwords.. even then it would be strange if i'm able to parse the password as a URL :-) (unparsable strings aren't sent to the server either)

**Comment by hpoul** [comment]
I think *displaying* of custom icons is finished. I've separated the open issues into:

1. Adding/selectig custom icos: #157
2. Rollout for dynamic website icons #158
