### ISSUE TITLE
F-Droid fails to build

### ISSUE THREAD

**Issue by licaon-kter** [authpass/authpass#70]
[design.codeux.authpass.fdroid_132.log.gz](https://github.com/authpass/authpass/files/4625280/design.codeux.authpass.fdroid_132.log.gz)

What are we missing?

**Comment by hpoul** [comment]
imho it is not the correct flutter version (which should dart 2.8) - the error message looks like it is not using dart <2.8.. it's possible that the 1.7.0 tag was moved, because it was a pre-release tag before, so maybe the fdroidserver used an old versrion? anyway.. i'll create a MR for using flutter 1.7.1 (which got released yesterday) just have to test building..
it would be really nice if there was an option to manage the srclibs dependency on my end (just like the version/build tag.. maybe as a third regex pattern in UpdateCheckData? :-) )

**Comment by hpoul** [comment]
build with 1.17.1 worked for me locally.. created a MR https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6785

```
✓ Built build/app/outputs/apk/fdroid/release/app-fdroid-release.apk (53.1MB).
INFO: Successfully built version 1.6.0 of design.codeux.authpass.fdroid
DEBUG: Using androguard from "/Users/herbert/dev/fdroidvenv/lib/python3.7/site-packages/androguard/__init__.py"
DEBUG: Checking build/design.codeux.authpass.fdroid/authpass/build/app/outputs/apk/fdroid/release/app-fdroid-release.apk
INFO: success: design.codeux.authpass.fdroid
INFO: Finished
INFO: 1 build succeeded
```

**Comment by licaon-kter** [comment]
I've seen this error before, eg. you specify stable or beta and you end up with a different commit.

https://gitlab.com/fdroid/fdroidserver/-/issues/743

**Comment by hpoul** [comment]
yeah, that's why the version `1.17.0` was referenced but it seems before it is actually released, it is still a moving target.. but `1.17.1` has been released now, so it should never change..

on the CIs (github actions, cirrus, travis) i simply download flutter on every build: https://github.com/authpass/authpass/blob/master/authpass/_tools/install_flutter.sh .. but it's using the flutter binary distribution, which is probably a no-go for fdroid..
