### ISSUE TITLE
Support for OneDrive sync

### ISSUE THREAD

**Issue by gabeweb** [authpass/authpass#71]
Lately Microsoft has been "open" a bit, but is there a chance to offer OneDrive sync?

**Comment by hpoul** [comment]
it was a bit more effort than i've anticipated, but i've now finished a first version, maybe you can give the sideloaded version a try: https://github.com/authpass/authpass/actions/runs/108670589

otherwise i'll probably release a new version within the next 1 or 2 days.. but have to test whether all other file storage options are still working :-)

**Comment by hpoul** [comment]
Since this has been implemented and released for a while.. I'll close this ;-)
