### ISSUE TITLE
Restore AuthPass kdbx file from the XML Debug Log

### ISSUE THREAD

**Issue by gCube** [authpass/authpass#72]
After trying to import the AuthPass keyfile into KeePass, it doesn't recognize nor read any data.

As i test, i have made a new DB file in AuthPass and uploaded this on the desktop version of KeePass.
Next, when importing the file, KeePass doesnt recognize this as a valid kdbx file.

**Comment by hpoul** [comment]
what exactly do you mean with XML Debug Log? produced by AuthPass? How?

Also right now it should work as expected to use a Keepass produced file in AuthPass, make and save changes and later open it back in Keepass. (ie. preexisting files should stay compatible, otherwise please let me know the versions of AuthPass and Keepass, and if at all possible provide an example file for me to reproduce the problem).

Newly created files which originated in AuthPass are not yet fully compatible. there are a few meta fields which are not created which Keepass is expecting, shouldn't be a big problem to make it compatible though.

**Comment by hpoul** [comment]
okay, never mind.. i just discovered that the fdroid version has the wrong configuration and has debug mode activated 🤦️ .. that 'DEBUG: Copy XML' button shouldn't be visible at all..and is only meant for that.. debugging..

there is no way to restore the file only from that debug XML structure, because the salt for encryption of protected values is stored in the binary header..

do you still have your original file in authpass?

**Comment by gCube** [comment]
My android crashed right after a update. Before i started the update process i managed to make a backup of all my other files and applications. 
As i tried to access the internal folder of the AuthPass.app/flutter/**.kdbx i couldnt find or see any files located there. The storage was protected and i could not extract the .kdbx file. Thus made me believe that i had enough with the .XML(DEBUG) as the structure seemed very similar.

Sadly enough not... :facepalm: 

I managed to restore my passwords manually but that took me a week.

**Comment by hpoul** [comment]
The next version for fdroid will no longer have that debug option visible.. I'll keep this issue open to think about options to prevent this from happening to other users.. either one of those two

1. add a warning for users who use internal storage
2. Make the internal folder backup-able.. this should be easy for Android with play services and ios, as there is a backup mechanism.. but i don't think there is something similar for fdroid?

**Comment by hpoul** [comment]
fyi, there is now a reminder to use a cloud service. So i think this issue is resolved.
