### ISSUE TITLE
Import/Export from other formats (json, csv)

### ISSUE THREAD

**Issue by matesurano** [authpass/authpass#83]
I will try to explain the features with examples. 
1. Import/export passwords (like json,csv etc)
2. When i open an app/browser with autofill fields,>> there should be a prompt by authpass(already available in authpass)and >> after clicking that prompt next step is >>opening authpass with biometrics>>Here authpass asks me to select the concerned entry(credentials) and then it autofills.BUT IT SHOULD  AUTOMATICALLY SELECT  THE CONCERNED ENTRY according to the app id/ or website address(if in browser). Most of PWM does this.
3. Autocopy or autofill TOTP. For example if a website has totp enabled,  after autofilling the login n password authpass should automatically copy the relevant Totp code and we just paste it in the field(just like Enpass). OR, authpass can give us a popup  notification of the TOTP with an option to copy the same(just like Dashlane).

These are  the missing features as far  as I  can remember. Thanks.

**Comment by hpoul** [comment]
Hi, thanks for the feedback. I have extracted 2 and 3 into separate issues:

2. #84 
3. #85 

it's easier to keep track of everything when each feature corresponds to a single issue. #84  sounds to me like the most important one.. #85 is a bit more complicated..

**Comment by MrTeeXD** [comment]
I would love to see this implemented sometime since I use something thats not Open Source and that I wish to switch to this.

**Comment by hpoul** [comment]
@MrTeeXD what kind of format would you like to see? btw. for now you could use for example Keepass to convert your database to kdbx, AuthPass is completely compatible with the format of keepass. 
for CSV you can also use Keeweb: https://app.keeweb.info/ simply drag & drop a CSV file, import it.. and then save the `kdbx` file.. which again is completely compatible with AuthPass.

**Comment by MrTeeXD** [comment]
Ahh thank you. I am patiently waiting for the Windows Version

**Comment by hpoul** [comment]
@MrTeeXD unfortunately i'm not sure how soon the windows version will be ready.. my only windows machine currently crashes with the flutter embedder on windows: https://github.com/flutter/flutter/issues/51286#issuecomment-646481263 ... until I can get it to run on that ancient pc, I can't port the few native plugins..

**Comment by MrTeeXD** [comment]
Understandable. Goodluck man

**Comment by hpoul** [comment]
@MrTeeXD just to note, the windows version has since been released, have you given it a try?

**Comment by MrTeeXD** [comment]
Yes I have, works perfectly

**Comment by hpoul** [comment]
Moving 'import' functionality into new Issue to keep better track of it: https://github.com/authpass/authpass/issues/152

closing this issue, as I don't  think there is anything left. If you have any import formats which are commonly used please add your comment to #152

**Comment by jwmh** [comment]
Q: Is there an Export db feature implemented??

**Comment by hpoul** [comment]
@jwmh No, also this is not the place for questions or feature requests.. maybe you could elaborate more about your use case and requirements in the forum https://forum.authpass.app/

**Comment by jwmh** [comment]
@hpoul sorry. i was following up on the OP's #1 request.  I see that you added the Import feature (great!), my q was re the other half of the OP's feature request..... And responding to your comment "also this is not the place for...feature requests..." Has that policy changed since the OP posted above???

**Comment by hpoul** [comment]
@jwmh No there is no import feature, see #152 Or see [this FAQ in the forum: https://forum.authpass.app/t/how-can-i-import-my-existing-passwords-into-authpass/24](https://forum.authpass.app/t/how-can-i-import-my-existing-passwords-into-authpass/24). - There is no export either, because imho kdbx format is pretty much as close to an open standard as you can get.. as there are dozens of libraries, and hundreds of clients which support it. If you have a special use case you can elaborate in the forum for [feature requests/discussions](https://forum.authpass.app/c/feature-discussions/7).

I would like to have issues only for "actionable" tasks which provide value. having a vague "export" feature which does not define what, why, how requires more discussion.. This is why i prefer the forum for this. And why when you check out the [new issue](https://github.com/authpass/authpass/issues/new/choose) on github this is mentioned as well.

fwiw, closed issues are hardly ever a good place for discussions 😅️ although i'd admit that that "export" part of the initial request might have been lost. (since there where 4 issues bundled into one). But feel free to give more explanation in the feature discussions and we see how much interest there is into a feature like it.
