### ISSUE TITLE
Linux: folder icon broken

### ISSUE THREAD

**Issue by nesimtunc** [authpass/authpass#95]
I believe in the folder / group structure of `Keepass` should be same when imported. Now, kind of lost, all in one tree.

PS: Just noticed that folder icon in the list is broken on Ubuntu when I saw on Mac OS.

**Comment by hpoul** [comment]
The group structure is still there. You can see it, filter it, change it, use it in searches.. not sure what else there is
Also see #75 

You are right about the folder icon on Linux though.. will keep this issue open for now to track that bug

**Comment by nesimtunc** [comment]
I see the group under the items, but I mean is tree list like this: https://keepass.info/screenshots/keepass_2x/main_big.png

This way is difficult to find, unless filtering yeah but when you over thousand of password, it's really messy

**Comment by hpoul** [comment]
See #75 .. you have the group tree in the filter, i see no benefit in creating another tree view for passwords.. if your have more use case or ideas to contribute feel free to add them to #75 .. but right now i still don't understand the use case for browsing through an endless tree of passwords rather than just searching.. and fyi I've got enough passwords as well..
